ALTER TABLE library ALTER COLUMN icon DROP NOT NULL;
ALTER TABLE library ALTER COLUMN icon_type DROP NOT NULL;

ALTER TABLE magic_shelf ALTER COLUMN icon DROP NOT NULL;
ALTER TABLE magic_shelf ALTER COLUMN icon_type DROP NOT NULL;

ALTER TABLE shelf ALTER COLUMN icon DROP NOT NULL;
ALTER TABLE shelf ALTER COLUMN icon_type DROP NOT NULL;
