CREATE TABLE IF NOT EXISTS oidc_group_mapping (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    oidc_group_claim VARCHAR(255) NOT NULL UNIQUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    permissions TEXT,
    library_ids TEXT,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
